-- Allow public inserts for seeding
CREATE POLICY "Allow public insert" ON agents FOR INSERT WITH CHECK (true);

-- Insert agents
INSERT INTO agents (name, location, bazaraki_url, listing_count, google_rating, google_reviews_count) VALUES
  ('1 Home Cyprus', 'Paphos', 'https://www.bazaraki.com/c/1HomeCyprus/', 33, NULL, 0),
  ('21 Property Finder Ltd', 'Nicosia', 'https://www.bazaraki.com/c/21finder/', 478, NULL, 0),
  ('2BUY&2LET', 'Limassol', 'https://www.bazaraki.com/c/2BUY2LET/', 488, NULL, 0),
  ('4BUY&SELL', 'Limassol', 'https://www.bazaraki.com/c/4BUYANDSELL/', 348, 5, 64),
  ('A 20 Real Estate', 'Paphos', 'https://www.bazaraki.com/c/A20realestate/', 19, NULL, 0),
  ('ABOVE ALL PROPERTIES LTD', 'Limassol', 'https://www.bazaraki.com/c/AboveAll/', 66, NULL, 0),
  ('AGD GOLDEN WAY LTD', 'Nicosia', 'https://www.bazaraki.com/c/AGDGOLDENWAY/', 12, NULL, 0),
  ('A. KAILIS ESTATES LTD', 'Nicosia', 'https://www.bazaraki.com/c/kailisproperties/', 19, NULL, 0),
  ('Aktihomes', 'Famagusta', 'https://www.bazaraki.com/c/aktihomes/', 94, NULL, 0),
  ('Albrook Properties Limited', 'Limassol', 'https://www.bazaraki.com/c/Homelink/', 28, NULL, 0),
  ('Altia', 'Nicosia', 'https://www.bazaraki.com/c/Altia/', 462, NULL, 0),
  ('Amaze Arena Properties -Valuers Ltd', 'Limassol', 'https://www.bazaraki.com/c/arenaproperties/', 68, NULL, 0),
  ('ANDREAS CHARALAMBOUS PROPERTIES', 'Nicosia', 'https://www.bazaraki.com/c/andreascharalambousproperties/', 11, NULL, 0),
  ('Andreas Xenofontos Developers Ltd', 'Limassol', 'https://www.bazaraki.com/c/andreasxenofontos/', 5, NULL, 0),
  ('A.N.K. RealDream Estate LTD', 'Nicosia', 'https://www.bazaraki.com/c/realdreamestate/', 14, NULL, 0),
  ('ANTA Estates', 'Limassol', 'https://www.bazaraki.com/c/ANTAestates/', 11, NULL, 0),
  ('AREA ESTATE AGENTS', 'Nicosia', 'https://www.bazaraki.com/c/areaestate/', 33, NULL, 0),
  ('Arto Estates', 'Limassol', 'https://www.bazaraki.com/c/artoestates/', 144, 4.6, 15),
  ('A&T OASIS LUXURY HOUSES LTD', 'Larnaca', 'https://www.bazaraki.com/c/oasis/', 2, NULL, 0),
  ('Blue Sky Houses', 'Paphos', 'https://www.bazaraki.com/c/BlueSkyHouses/', 9, 4.9, 59),
  ('BRILLIK LTD', 'Limassol', 'https://www.bazaraki.com/c/kaif_residence/', 1, NULL, 0),
  ('BUILDIA CONSTRUCTIONS LTD', 'Limassol', 'https://www.bazaraki.com/c/BUILDIA/', 5, NULL, 0),
  ('Casa Mare Real Estate', 'Nicosia', 'https://www.bazaraki.com/c/casamare/', 23, NULL, 0),
  ('CAV Real Estate Solutions Larnaca', 'Larnaca', 'https://www.bazaraki.com/c/CAVlarnaca/', 2, NULL, 0),
  ('CENTURY 21', 'Limassol', 'https://www.bazaraki.com/c/century21/', 932, 4.6, 37),
  ('Charm Developments', 'Nicosia', 'https://www.bazaraki.com/c/charmdevelopments/', 10, NULL, 0),
  ('Chestertons Cyprus Residential', 'Paphos', 'https://www.bazaraki.com/c/ChestertonsCyprusResidential/', 8, NULL, 0),
  ('CHRIS MICHAEL PROPERTY GROUP', 'Limassol', 'https://www.bazaraki.com/c/chrismichaelpropertygroup/', 500, 4.9, 38),
  ('Chrissaf Real Estate', 'Limassol', 'https://www.bazaraki.com/c/Chrissafrealestate/', 20, NULL, 0),
  ('CITYBRICK', 'Nicosia', 'https://www.bazaraki.com/c/CITYBRICK/', 6, NULL, 0),
  ('CLICKHOME CYPRUS', 'Limassol', 'https://www.bazaraki.com/c/clickhome/', 462, NULL, 0),
  ('Comark Estates', 'Limassol', 'https://www.bazaraki.com/c/comarkestates/', 62, 4.8, 21),
  ('CORAL BLU ESTATES', 'Paphos', 'https://www.bazaraki.com/c/coralblu/', 9, NULL, 0),
  ('C.T. PROPERTY', 'Limassol', 'https://www.bazaraki.com/c/ctproperty/', 10, NULL, 0),
  ('Culpro Estates Ltd', 'Limassol', 'https://www.bazaraki.com/c/culproestates/', 31, NULL, 0),
  ('Cyperland Developers', 'Paphos', 'https://www.bazaraki.com/c/cyperland/', 10, NULL, 0),
  ('Cyprian Star Estates', 'Paphos', 'https://www.bazaraki.com/c/cyprianstarestates/', 15, NULL, 0),
  ('Cyprus Domus', 'Limassol', 'https://www.bazaraki.com/c/cyprusdomus/', 138, NULL, 0),
  ('Cyprus Sothebys International Realty', 'Paphos', 'https://www.bazaraki.com/c/sothebys/', 916, 4.8, 43),
  ('D.A.C. PROPERTIES & CONSTRUCTIONS LTD', 'Limassol', 'https://www.bazaraki.com/c/DAC/', 31, NULL, 0),
  ('DAKAR MOTORS LTD', 'Larnaca', 'https://www.bazaraki.com/c/DAKARMOTORS/', 18, NULL, 0),
  ('David Spyrou Estates LTD', 'Larnaca', 'https://www.bazaraki.com/c/davidestates/', 85, 4.2, 36),
  ('Delfi Properties', 'Nicosia', 'https://www.bazaraki.com/c/delfiproperties/', 492, 4.5, 21),
  ('DemPro Estate Agents', 'Paphos', 'https://www.bazaraki.com/c/dempro/', 5, NULL, 0),
  ('DESTATE LTD', 'Larnaca', 'https://www.bazaraki.com/c/destate/', 25, NULL, 0),
  ('DEVELOPERS A. N. Stasis Estates PLC', 'Paphos', 'https://www.bazaraki.com/c/stasisestates/', 8, NULL, 0),
  ('D Fitzgerald Marketing', 'Paphos', 'https://www.bazaraki.com/c/fitzgeraldmarketing/', 13, NULL, 0),
  ('DOME REAL ESTATE', 'Paphos', 'https://www.bazaraki.com/c/dome/', 26, 4.7, 29),
  ('DOM Real Estate', 'Limassol', 'https://www.bazaraki.com/c/domrealestate/', 2000, NULL, 0),
  ('Doorway Real Estate', 'Limassol', 'https://www.bazaraki.com/c/Doorway/', 491, 5, 105),
  ('Down Town Cyprus Sales and Rentals', 'Paphos', 'https://www.bazaraki.com/c/downtowncyprus/', 22, 4.8, 25),
  ('E.G. GALLERY ESTATE', 'Limassol', 'https://www.bazaraki.com/c/galleryestate/', 297, NULL, 0),
  ('E. NEARCHOU ESTATE AGENTS LTD', 'Limassol', 'https://www.bazaraki.com/c/nearchouestates/', 9, NULL, 0),
  ('EUROESTATE S.D AGENCY LTD', 'Larnaca', 'https://www.bazaraki.com/c/EUROESTATE/', 19, NULL, 0),
  ('Everest Houses', 'Nicosia', 'https://www.bazaraki.com/c/everestconstruction/', 11, NULL, 0),
  ('Evgenios Vrionides Estate Ltd', 'Limassol', 'https://www.bazaraki.com/c/evgeniosvrionidesestates/', 39, NULL, 0),
  ('EVGENIOS VRIONIDES REAL ESTATE LTD', 'Limassol', 'https://www.bazaraki.com/c/evgeniosvrionidesltd/', 19, NULL, 0),
  ('F.G. Fotiou Developers & Construction Ltd', 'Limassol', 'https://www.bazaraki.com/c/fgfotioudevelopersandconstructionltd/', 1, NULL, 0),
  ('First class Homes LTD', 'Limassol', 'https://www.bazaraki.com/c/firstclasshomse/', 18, NULL, 0),
  ('Fox Limassol Main Branch', 'Limassol', 'https://www.bazaraki.com/c/foxlimassol/', 16, NULL, 0),
  ('Fox Molos Limassol', 'Limassol', 'https://www.bazaraki.com/c/foxlim/', 18, NULL, 0),
  ('FOX Smart Estate Agency', 'Paphos', 'https://www.bazaraki.com/c/foxpaphos/', 15, NULL, 0),
  ('Fox Smart Estate Agency Network LTD', 'Nicosia', 'https://www.bazaraki.com/c/foxrealty/', 60, 4.3, 52),
  ('Foytina Real Estate Agency - Sales & Rentals in Cyprus', 'Larnaca', 'https://www.bazaraki.com/c/foytina/', 15, NULL, 0),
  ('Galaxia Estates', 'Limassol', 'https://www.bazaraki.com/c/galaxiaestates/', 94, 4.7, 29),
  ('Georepa Estates Ltd', 'Limassol', 'https://www.bazaraki.com/c/Georepaestates/', 7, NULL, 0),
  ('GIS DEVELOPERS', 'Limassol', 'https://www.bazaraki.com/c/gisdevelopers/', 1, NULL, 0),
  ('GPA Upgraded Homes LTD', 'Limassol', 'https://www.bazaraki.com/c/gpaupgradedhomes/', 14, NULL, 0),
  ('GREEN Properties Land Developers', 'Nicosia', 'https://www.bazaraki.com/c/greenpropertiescy/', 7, NULL, 0),
  ('HHP residences', 'Nicosia', 'https://www.bazaraki.com/c/HHPresidences/', 6, NULL, 0),
  ('HOME 4U REAL ESTATES', 'Nicosia', 'https://www.bazaraki.com/c/HOME4U/', 20, NULL, 0),
  ('HOME CITY INVESTMENTS', 'Larnaca', 'https://www.bazaraki.com/c/Homecityinvestments/', 5, NULL, 0),
  ('Hubloc Investments Ltd', 'Limassol', 'https://www.bazaraki.com/c/Hubloc/', 6, NULL, 0),
  ('INHOME REAL ESTATE', 'Limassol', 'https://www.bazaraki.com/c/inhome/', 9, NULL, 0),
  ('INREALTY', 'Limassol', 'https://www.bazaraki.com/c/inrealty/', 5, NULL, 0),
  ('INTERLIVING GROUP', 'Larnaca', 'https://www.bazaraki.com/c/Interlivinggroup/', 8, NULL, 0),
  ('INTER-M LTD', 'Limassol', 'https://www.bazaraki.com/c/intermproperties/', 88, NULL, 0),
  ('IPN Cyprus', 'Limassol', 'https://www.bazaraki.com/c/ipncyprus/', 15, NULL, 0),
  ('John Taylor Cyprus', 'Limassol', 'https://www.bazaraki.com/c/johntaylorcyprus/', 8, NULL, 0),
  ('John Theodorou Property Developers', 'Limassol', 'https://www.bazaraki.com/c/johntheodorou/', 8, NULL, 0),
  ('KALAMON HOMES', 'Larnaca', 'https://www.bazaraki.com/c/kalamonhomes/', 11, NULL, 0),
  ('Kalogirou Real Estate', 'Larnaca', 'https://www.bazaraki.com/c/kalogirourealestate/', 1491, 4.8, 389),
  ('Kantou Developers', 'Nicosia', 'https://www.bazaraki.com/c/kantoudevelopers/', 10, NULL, 0),
  ('Kasinos Real Estate', 'Nicosia', 'https://www.bazaraki.com/c/kasinosrealestate/', 15, NULL, 0),
  ('KAZO REAL ESTATES', 'Limassol', 'https://www.bazaraki.com/c/kazorealestate/', 2000, 3.9, 27),
  ('KEYCY Real Estate', 'Limassol', 'https://www.bazaraki.com/c/keycy/', 30, NULL, 0),
  ('K.Kypros Estates', 'Nicosia', 'https://www.bazaraki.com/c/kyprosestates/', 10, NULL, 0),
  ('Kpi Pieris Construction & Development LTD', 'Nicosia', 'https://www.bazaraki.com/c/KPIPIERIS/', 5, NULL, 0),
  ('KW SEVEN', 'Larnaca', 'https://www.bazaraki.com/c/KWSEVEN/', 41, NULL, 0),
  ('Landbank Property Consultants Ltd', 'Nicosia', 'https://www.bazaraki.com/c/Landbank/', 358, NULL, 0),
  ('LANDPORT LIMITED', 'Limassol', 'https://www.bazaraki.com/c/landport/', 30, NULL, 0),
  ('LEMONMARIA DEVELOPERS LTD', 'Paphos', 'https://www.bazaraki.com/c/Lemonmaria/', 5, NULL, 0),
  ('LEPTOS ESTATES', 'Paphos', 'https://www.bazaraki.com/c/leptos/', 10, 4.3, 34),
  ('LETO Properties Cyprus', 'Limassol', 'https://www.bazaraki.com/c/letoproperties/', 33, NULL, 0),
  ('LEXTRUS REAL ESTATE LTD', 'Larnaca', 'https://www.bazaraki.com/c/lextrusrealestate/', 493, NULL, 0),
  ('Life Realty Cyprus', 'Limassol', 'https://www.bazaraki.com/c/LifeRealty/', 776, 4.9, 29),
  ('Magic Properties Limassol', 'Limassol', 'https://www.bazaraki.com/c/magicpropertiescy/', 5, NULL, 0),
  ('Marinos Kineyirou Estate Agencies Ltd', 'Larnaca', 'https://www.bazaraki.com/c/kineyirouestates/', 100, 4.2, 86),
  ('MARIOS STAVROU AUTO', 'Limassol', 'https://www.bazaraki.com/c/MSA/', 12, NULL, 0),
  ('M&G Developers', 'Limassol', 'https://www.bazaraki.com/c/mgdevelopers/', 8, NULL, 0),
  ('Miranda Exclusive', 'Nicosia', 'https://www.bazaraki.com/c/mirandaexclusive/', 14, NULL, 0),
  ('MPA Property Promoters & Consultants Ltd', 'Nicosia', 'https://www.bazaraki.com/c/mpaproperty/', 789, 4.9, 99),
  ('M.Residence Ltd', 'Nicosia', 'https://www.bazaraki.com/c/mresidence/', 2000, 4.9, 133),
  ('NCH REAL ESTATE', 'Nicosia', 'https://www.bazaraki.com/c/nch/', 1498, 4.5, 13),
  ('Nelaza Ltd', 'Nicosia', 'https://www.bazaraki.com/c/Nelazaltd/', 27, NULL, 0),
  ('Next Home Estate Agency', 'Larnaca', 'https://www.bazaraki.com/c/nexthomecyprus/', 13, NULL, 0),
  ('NICOLAOU ESTATES', 'Limassol', 'https://www.bazaraki.com/c/nicolaouestates/', 250, 5, 6),
  ('NiSea', 'Limassol', 'https://www.bazaraki.com/c/nisea/', 195, NULL, 0),
  ('N.K. SmartAssets Ltd', 'Limassol', 'https://www.bazaraki.com/c/SmartAssets/', 2450, NULL, 0),
  ('Onlineproperties', 'Nicosia', 'https://www.bazaraki.com/c/onlinepropertiesestate/', 43, NULL, 0),
  ('Online Properties', 'Nicosia', 'https://www.bazaraki.com/c/onlineproperties/', 69, NULL, 0),
  ('OPTIMUS REAL ESTATE AGENCY', 'Limassol', 'https://www.bazaraki.com/c/optimusrealestate/', 9, NULL, 0),
  ('PAFILIA', 'Paphos', 'https://www.bazaraki.com/c/pafilia/', 23, 4.8, 16),
  ('Paliren Casa', 'Nicosia', 'https://www.bazaraki.com/c/palirencasaestates/', 9, NULL, 0),
  ('PALIREN CASA LTD', 'Nicosia', 'https://www.bazaraki.com/c/palirencasa/', 23, NULL, 0),
  ('Pandomus Group', 'Limassol', 'https://www.bazaraki.com/c/pandomusgroup/', 10, NULL, 0),
  ('Patmos Estate Agency', 'Nicosia', 'https://www.bazaraki.com/c/PatmosEstate/', 18, NULL, 0),
  ('PAVLOU', 'Larnaca', 'https://www.bazaraki.com/c/pavlouestates/', 18, NULL, 0),
  ('PeakPoint Real Estate', 'Nicosia', 'https://www.bazaraki.com/c/PeakPointRealEstate/', 9, NULL, 0),
  ('PetroskyriacouGroup', 'Nicosia', 'https://www.bazaraki.com/c/petroskyriacou/', 37, NULL, 0),
  ('P.G.H. Cypriani Estate Agents', 'Nicosia', 'https://www.bazaraki.com/c/cyprianiestates/', 14, NULL, 0),
  ('PHN VALUE ESTATES', 'Larnaca', 'https://www.bazaraki.com/c/phnvalue/', 2, NULL, 0),
  ('PIÑATAS GROUP', 'Limassol', 'https://www.bazaraki.com/c/pinatas/', 5, NULL, 0),
  ('Plasis Real Estate Cyprus', 'Limassol', 'https://www.bazaraki.com/c/plasisrealestatecyprus/', 92, NULL, 0),
  ('Plaza Estates Ltd.', 'Limassol', 'https://www.bazaraki.com/c/plazaestates/', 21, NULL, 0),
  ('Plus Wise Estates', 'Larnaca', 'https://www.bazaraki.com/c/Pluswiseestatesltd/', 489, NULL, 0),
  ('P.N.NICOLAOU ESTATES LTD', 'Nicosia', 'https://www.bazaraki.com/c/pnnicolaou/', 249, NULL, 0),
  ('POUROS DEVELOPMENTS', 'Limassol', 'https://www.bazaraki.com/c/pouros/', 25, NULL, 0),
  ('P.Pericleous Real Estate', 'Paphos', 'https://www.bazaraki.com/c/Ppericleousrealestate/', 10, NULL, 0),
  ('Prime Property P.P. LTD', 'Limassol', 'https://www.bazaraki.com/c/bbf/', 12, NULL, 0),
  ('PropertyArt Cy Ltd', 'Limassol', 'https://www.bazaraki.com/c/propertyart/', 21, NULL, 0),
  ('Property One Limassol', 'Limassol', 'https://www.bazaraki.com/c/propertyonelimassol/', 59, NULL, 0),
  ('Property Partner', 'Limassol', 'https://www.bazaraki.com/c/propertypartner/', 13, NULL, 0),
  ('Property Portal', 'Nicosia', 'https://www.bazaraki.com/c/propertyportal/', 19, NULL, 0),
  ('PROPERTY PRO', 'Nicosia', 'https://www.bazaraki.com/c/propertyprocy/', 35, NULL, 0),
  ('Propwell Group', 'Larnaca', 'https://www.bazaraki.com/c/propwellestate/', 10, NULL, 0),
  ('Quality Home Developers', 'Paphos', 'https://www.bazaraki.com/c/qualityhomedevelopers/', 5, NULL, 0),
  ('Rasbery Properties - Licensed Estate Agents.', 'Limassol', 'https://www.bazaraki.com/c/RASBERY/', 11, NULL, 0),
  ('RealDeal Estates', 'Limassol', 'https://www.bazaraki.com/c/realdeal/', 496, NULL, 0),
  ('REALSOL CYPRUS LTD', 'Paphos', 'https://www.bazaraki.com/c/getawayhomes/', 369, NULL, 0),
  ('Realty 360', 'Famagusta', 'https://www.bazaraki.com/c/Realty360/', 12, NULL, 0),
  ('REMAX CYPRUS', 'Limassol', 'https://www.bazaraki.com/c/remaxcyprus/', 611, 4.4, 58),
  ('RENIK', 'Nicosia', 'https://www.bazaraki.com/c/renik/', 13, NULL, 0),
  ('Revia Estates', 'Limassol', 'https://www.bazaraki.com/c/reviaestates/', 10, NULL, 0),
  ('S Droussiotis Estates LTD', 'Limassol', 'https://www.bazaraki.com/c/Droussiotis/', 11, NULL, 0),
  ('Sioferos Real Estate', 'Limassol', 'https://www.bazaraki.com/c/sioferos/', 281, 4.8, 55),
  ('SOL Properties', 'Limassol', 'https://www.bazaraki.com/c/solproperties/', 14, NULL, 0),
  ('SOTIRIS AVRAAM', 'Nicosia', 'https://www.bazaraki.com/c/sotirisavraamandsons/', 13, NULL, 0),
  ('Square One', 'Limassol', 'https://www.bazaraki.com/c/squareone/', 24, NULL, 0),
  ('Starmax Real Estate Agency', 'Larnaca', 'https://www.bazaraki.com/c/starmax/', 4, NULL, 0),
  ('Stylianides Group', 'Limassol', 'https://www.bazaraki.com/c/stylianidesgroup/', 7, NULL, 0),
  ('SVA Estates', 'Limassol', 'https://www.bazaraki.com/c/svaestates/', 486, 5, 30),
  ('Sweet Home Estates', 'Famagusta', 'https://www.bazaraki.com/c/sweethome/', 239, NULL, 0),
  ('SYNERGY ESTATE AGENTS', 'Nicosia', 'https://www.bazaraki.com/c/synergyestates/', 323, NULL, 0),
  ('TEAM WORX PROPERTY', 'Limassol', 'https://www.bazaraki.com/c/teamworx/', 12, NULL, 0),
  ('The HERITAGE', 'Limassol', 'https://www.bazaraki.com/c/theheritage/', 14, NULL, 0),
  ('ThePropertyHouse', 'Limassol', 'https://www.bazaraki.com/c/thepropertyhouse/', 61, 4.9, 48),
  ('TLV Developers', 'Limassol', 'https://www.bazaraki.com/c/tlvdevelopers/', 3, NULL, 0),
  ('Tommys Real Estate Agency', 'Limassol', 'https://www.bazaraki.com/c/tommysestate/', 7, NULL, 0),
  ('Urban Keys', 'Nicosia', 'https://www.bazaraki.com/c/urbankeys/', 29, NULL, 0),
  ('Vivo Realty', 'Limassol', 'https://www.bazaraki.com/c/vivorealty/', 33, NULL, 0),
  ('Vizus Group', 'Limassol', 'https://www.bazaraki.com/c/Vizus/', 11, NULL, 0),
  ('Waves & Noble Property Management', 'Paphos', 'https://www.bazaraki.com/c/wavesnoblepropertymanagement/', 1, NULL, 0),
  ('WinWin Estates Ltd', 'Limassol', 'https://www.bazaraki.com/c/WinWin/', 17, NULL, 0),
  ('Xenios Xenofontos constructions and developers ltd', 'Limassol', 'https://www.bazaraki.com/c/xeniosxenofontos/', 1, NULL, 0),
  ('Yiannakas Estates', 'Nicosia', 'https://www.bazaraki.com/c/yiannakasestates/', 3, NULL, 0),
  ('Y.L.Luxury Homes Ltd', 'Limassol', 'https://www.bazaraki.com/c/ylluxuryhomes/', 19, NULL, 0),
  ('Y.L.Luxury Homes Ltd', 'Paphos', 'https://www.bazaraki.com/c/ylestates/', 26, NULL, 0),
  ('Zourides Real Estate', 'Larnaca', 'https://www.bazaraki.com/c/zourides/', 121, NULL, 0),
  ('ΣΑΣΑ ΓΕΩΡΓΙΑΔΟΥ ΕΓΓΕΓΡΑΜΜΕΝΗ ΚΤΗΜΑΤΟΜΕΣΙΤΡΙΑ', 'Nicosia', 'https://www.bazaraki.com/c/sasageorgiadou/', 11, NULL, 0),
  ('CSC Zyprus Property Group Ltd', 'Nicosia', 'https://www.bazaraki.com/c/zyprus/', 11, NULL, 0),
  ('Quastilo Properties', 'Limassol', 'https://www.bazaraki.com/c/quastiloproperties/', 98, NULL, 0),
  ('Monday Square', 'Larnaca', 'https://www.bazaraki.com/c/MondaySquare/', 96, NULL, 0),
  ('Zyprus Real Estate', 'Limassol', 'https://www.bazaraki.com/c/Voopa/', 22, 4.6, 25),
  ('3L Estates', 'Larnaca', 'https://www.bazaraki.com/c/3lestates/', 5, NULL, 0),
  ('Admare Property', 'Limassol', 'https://www.bazaraki.com/c/admareproperty/', 12, NULL, 0),
  ('Arena Properties', 'Famagusta', 'https://www.bazaraki.com/c/arenapropertiesagents/', 1000, NULL, 0),
  ('Axxelus cars4U', 'Larnaca', 'https://www.bazaraki.com/c/axxeluscars4u/', 6, NULL, 0),
  ('BLV Properties Cyprus', 'Limassol', 'https://www.bazaraki.com/c/blvpropertiescyprus/', 6, NULL, 0),
  ('ChapterOne Properties Ltd', 'Paphos', 'https://www.bazaraki.com/c/ChapterOneProperties/', 498, NULL, 0),
  ('Chris Tofi Real Estate Agency Ltd', 'Limassol', 'https://www.bazaraki.com/c/christofiestates/', 12, NULL, 0),
  ('CIC PROPERTIES', 'Larnaca', 'https://www.bazaraki.com/c/cynvestcorealestate/', 199, NULL, 0),
  ('Click Home Cyprus', 'Limassol', 'https://www.bazaraki.com/c/clickhomecyprus/', 14, NULL, 0),
  ('C.N.C TAKIANA ENTERPRISES LTD', 'Limassol', 'https://www.bazaraki.com/c/takiana/', 16, NULL, 0),
  ('C.N.C TAKIANA ENTERPRISES LTD', 'Limassol', 'https://www.bazaraki.com/c/cnctakiana/', 22, NULL, 0),
  ('Concept Realty', 'Paphos', 'https://www.bazaraki.com/c/conceptrealty/', 45, NULL, 0),
  ('C.Y. EXELAND LTD', 'Limassol', 'https://www.bazaraki.com/c/exelandcy/', 84, NULL, 0),
  ('CYPPRO Realty by L.Constantinou Co Ltd', 'Limassol', 'https://www.bazaraki.com/c/cypprorealty/', 13, NULL, 0),
  ('CYPRIANO ESTATE AGENTS', 'Paphos', 'https://www.bazaraki.com/c/cyprianoproperty/', 500, NULL, 0),
  ('CYTERRE REAL ESTATES LTD', 'Nicosia', 'https://www.bazaraki.com/c/cyterre/', 23, NULL, 0),
  ('Domenica Group', 'Paphos', 'https://www.bazaraki.com/c/Domenicagroup/', 8, NULL, 0),
  ('DOMO Properties', 'Limassol', 'https://www.bazaraki.com/c/DomoProperties/', 10, NULL, 0),
  ('Dot Real Estates', 'Nicosia', 'https://www.bazaraki.com/c/dotrealestate/', 17, NULL, 0),
  ('Dredaline Construction & Development LTD', 'Nicosia', 'https://www.bazaraki.com/c/Dredaline/', 1, NULL, 0),
  ('D. ZAVOS GROUP', 'Limassol', 'https://www.bazaraki.com/c/dzavosgroup/', 14, NULL, 0),
  ('EA LEMESOS  ESTATES', 'Limassol', 'https://www.bazaraki.com/c/ealemesosestates/', 74, NULL, 0),
  ('Easy Living Home Developers Ads', 'Larnaca', 'https://www.bazaraki.com/c/easyliving/', 7, NULL, 0),
  ('Elegant Cyprus Properties AT & PE Cyprus Homes Ltd', 'Paphos', 'https://www.bazaraki.com/c/elegantcyprusproperties/', 8, NULL, 0),
  ('Elit Blue ltd - Associate of Savills', 'Nicosia', 'https://www.bazaraki.com/c/elitblu/', 249, NULL, 0),
  ('EMERALD PROPERTIES', 'Limassol', 'https://www.bazaraki.com/c/emeraldproperties/', 98, NULL, 0),
  ('FIRST CLASS HOMES LTD', 'Limassol', 'https://www.bazaraki.com/c/firstclassmona/', 11, NULL, 0),
  ('FIRST CLASS HOMES LTD', 'Limassol', 'https://www.bazaraki.com/c/firstclasshomesmaria/', 16, NULL, 0),
  ('G ANTONIOU REAL ESTATE AGENCY', 'Nicosia', 'https://www.bazaraki.com/c/GANTONIOUREALESTATE/', 14, NULL, 0),
  ('GoGordian Real Estate', 'Nicosia', 'https://www.bazaraki.com/c/gogordian/', 423, NULL, 0),
  ('Homevision Real Estates Agent', 'Cyprus', 'https://www.bazaraki.com/c/HOMEVISION/', 8, NULL, 0),
  ('iMarkides Homes & Properties Ltd', 'Nicosia', 'https://www.bazaraki.com/c/imarkides/', 8, NULL, 0),
  ('Imperio Properties', 'Limassol', 'https://www.bazaraki.com/c/imperio/', 6, 4.4, 44),
  ('Investia Estate Agents Ltd', 'Larnaca', 'https://www.bazaraki.com/c/investiaestates/', 16, NULL, 0),
  ('IPC Developers Ltd', 'Larnaca', 'https://www.bazaraki.com/c/IPCDevelopers/', 9, NULL, 0),
  ('Joanmarino Real Estate Ltd', 'Limassol', 'https://www.bazaraki.com/c/joanmarino/', 23, NULL, 0),
  ('KADIS ESTATES', 'Nicosia', 'https://www.bazaraki.com/c/kadisestates/', 1000, NULL, 0),
  ('Karis Estates', 'Nicosia', 'https://www.bazaraki.com/c/karisestates/', 23, NULL, 0),
  ('KW Limassol', 'Limassol', 'https://www.bazaraki.com/c/kwsevenlimassol/', 63, NULL, 0),
  ('La Maison Estates', 'Nicosia', 'https://www.bazaraki.com/c/lamaisonestates/', 36, NULL, 0),
  ('La Mer Estates', 'Famagusta', 'https://www.bazaraki.com/c/LaMer/', 208, NULL, 0),
  ('Landoor Develompent', 'Larnaca', 'https://www.bazaraki.com/c/landoordevelopment/', 2, NULL, 0),
  ('Louis Estates', 'Limassol', 'https://www.bazaraki.com/c/louisestates/', 10, NULL, 0),
  ('Maisson Estate', 'Limassol', 'https://www.bazaraki.com/c/maissonproperty/', 26, NULL, 0),
  ('Majesty Real Estate', 'Limassol', 'https://www.bazaraki.com/c/majestyestates/', 494, NULL, 0),
  ('MARIOS ELIA REAL ESTATE', 'Nicosia', 'https://www.bazaraki.com/c/marioseliarealestate/', 2, NULL, 0),
  ('Mival Developers Ltd', 'Nicosia', 'https://www.bazaraki.com/c/mival/', 6, NULL, 0),
  ('M.K OPTION ESTATES LTD', 'Limassol', 'https://www.bazaraki.com/c/Optionestates/', 5, NULL, 0),
  ('MNM', 'Limassol', 'https://www.bazaraki.com/c/mnmestate/', 39, NULL, 0),
  ('Moneyhill Properties by IPN', 'Larnaca', 'https://www.bazaraki.com/c/MoneyhillPropertiesByIPN/', 12, NULL, 0),
  ('N&C Kyriakides Estates  Ltd', 'Larnaca', 'https://www.bazaraki.com/c/kyriakidesestates/', 15, NULL, 0),
  ('Nest & Co', 'Limassol', 'https://www.bazaraki.com/c/nestcy/', 99, NULL, 0),
  ('Nexus Elite Property Group', 'Larnaca', 'https://www.bazaraki.com/c/nexuseliteproperty/', 14, NULL, 0),
  ('N.G.M. Real Estate Ltd', 'Paphos', 'https://www.bazaraki.com/c/ngmrealestate/', 46, NULL, 0),
  ('NYKO PROPERTIES', 'Paphos', 'https://www.bazaraki.com/c/nykoproperties/', 16, NULL, 0),
  ('Omega Real Estate Cyprus', 'Nicosia', 'https://www.bazaraki.com/c/omegarealestate/', 289, NULL, 0),
  ('One Island Estates', 'Limassol', 'https://www.bazaraki.com/c/Oneisland/', 18, NULL, 0),
  ('Paschalis Theophanous Estates & Services Ltd', 'Nicosia', 'https://www.bazaraki.com/c/theophanousestates/', 24, NULL, 0),
  ('Path Property Ltd', 'Limassol', 'https://www.bazaraki.com/c/pathproperty/', 8, NULL, 0),
  ('P.H. SUNSHINE LUXURY VILLAS LTD', 'Nicosia', 'https://www.bazaraki.com/c/sunshineluxuryvillas/', 10, NULL, 0),
  ('PH.YIANGOU ESTATES', 'Nicosia', 'https://www.bazaraki.com/c/yiangouestates/', 87, NULL, 0),
  ('P.K ASSET DEALS', 'Larnaca', 'https://www.bazaraki.com/c/assetestates/', 11, NULL, 0),
  ('POULLARIS PROPERTIES', 'Nicosia', 'https://www.bazaraki.com/c/poullarisproperties/', 6, NULL, 0),
  ('Property Choice Ltd', 'Larnaca', 'https://www.bazaraki.com/c/propertychoice/', 145, NULL, 0),
  ('PropertyFate', 'Limassol', 'https://www.bazaraki.com/c/propertyfate/', 18, NULL, 0),
  ('Property Masters', 'Nicosia', 'https://www.bazaraki.com/c/propertymastersa/', 224, NULL, 0),
  ('Property One Real Estate Ltd', 'Nicosia', 'https://www.bazaraki.com/c/propertyone/', 14, NULL, 0),
  ('Properway', 'Nicosia', 'https://www.bazaraki.com/c/properway/', 8, NULL, 0),
  ('Pro Print', 'Nicosia', 'https://www.bazaraki.com/c/proprint/', 13, NULL, 0),
  ('Prospecta Development', 'Paphos', 'https://www.bazaraki.com/c/prospectadevelopment/', 7, NULL, 0),
  ('REACT ESTATES LTD', 'Nicosia', 'https://www.bazaraki.com/c/reactestates/', 28, NULL, 0),
  ('Sabbianco Properties', 'Nicosia', 'https://www.bazaraki.com/c/sabbiancoproperties/', 305, NULL, 0),
  ('Sakyrco Development', 'Limassol', 'https://www.bazaraki.com/c/sakyrco/', 3, NULL, 0),
  ('Sino Ocean Development Ltd.', 'Limassol', 'https://www.bazaraki.com/c/Sinooceandevelopment/', 3, NULL, 0),
  ('SLV Estates', 'Paphos', 'https://www.bazaraki.com/c/SLV/', 15, NULL, 0),
  ('Sotos Properties Ltd', 'Limassol', 'https://www.bazaraki.com/c/sotosproperties/', 31, NULL, 0),
  ('Tommys Estate Agency Chrysostomos Papageorgiou', 'Limassol', 'https://www.bazaraki.com/c/tommysestates/', 53, NULL, 0),
  ('Top Stay Homes Ltd', 'Limassol', 'https://www.bazaraki.com/c/topstayhomes/', 12, NULL, 0),
  ('VACHRICO Construction Ltd', 'Nicosia', 'https://www.bazaraki.com/c/vachrico/', 3, NULL, 0),
  ('VOUNIOTIS REAL ESTΑΤΕ AGENT', 'Limassol', 'https://www.bazaraki.com/c/Vouniotis/', 5, NULL, 0),
  ('ZOOQ ESTATES', 'Nicosia', 'https://www.bazaraki.com/c/Zooqestates/', 18, NULL, 0),
  ('Zyprus Property Group LTD', 'Limassol', 'https://www.bazaraki.com/c/zyprusrealestate/', 6, NULL, 0),
  ('Zyprus Real Estate', 'Limassol', 'https://www.bazaraki.com/c/Zyprus/', 12, NULL, 0),
  ('ΜΙΚΗΣ ΠΑΠΑΡΓΥΡΟΥ ΟΙΚΙΣΤΙΚΗ ΛΤΔ', 'Nicosia', 'https://www.bazaraki.com/c/mikispapargyrou/', 2, NULL, 0),
  ('Φρίξος Μηνά και Συνεργάτες Λτδ', 'Nicosia', 'https://www.bazaraki.com/c/Frixosmina/', 14, NULL, 0),
  ('MySpace Real Estate', 'Limassol', 'https://www.bazaraki.com/c/myspace/', 1670, NULL, 0),
  ('Property Masters', 'Nicosia', 'https://www.bazaraki.com/c/propertymastersltd/', 15, NULL, 0),
  ('EVGENIOS VRIONIDES REAL ESTATE LTD', 'Limassol', 'https://www.bazaraki.com/c/GeorgeNicolaou/', 12, NULL, 0),
  ('SYNERGY ESTATE AGENTS', 'Nicosia', 'https://www.bazaraki.com/c/synergyestatwagents/', 8, NULL, 0),
  ('K. Efthymiou Development Ltd', 'Limassol', 'https://www.bazaraki.com/c/kefthymioudevelopment/', 9, NULL, 0),
  ('El mundo real estate', 'Nicosia', 'https://www.bazaraki.com/c/elmundoangelos/', 8, NULL, 0),
  ('hairwaves', 'Larnaca', 'https://www.bazaraki.com/c/hairwaves/', 2, NULL, 0),
  ('PAVLOS PASCHALI REAL ESTATE LTD', 'Limassol', 'https://www.bazaraki.com/c/smartmoveonline/', 18, NULL, 0),
  ('S Droussiotis Estates', 'Limassol', 'https://www.bazaraki.com/c/sdroussiotis/', 42, NULL, 0),
  ('ΚΤΗΜΑΤΙΚΕΣ ΕΠΙΧΕΙΡΗΣΕΙΣ ΔΗΜΗΤΡΑ Α ΒΟΣΚΟΥ', 'Nicosia', 'https://www.bazaraki.com/c/Constantiaconstantinou/', 16, NULL, 0),
  ('C.A. SELECTIVE GROUP LTD', 'Limassol', 'https://www.bazaraki.com/c/yiangos/', 10, NULL, 0),
  ('C-more properties', 'Nicosia', 'https://www.bazaraki.com/c/cmorepropertiescy/', 60, NULL, 0),
  ('MATEIDES ESTATES CHRISTOS', 'Limassol', 'https://www.bazaraki.com/c/mateidesestates/', 19, NULL, 0),
  ('Mateides Real Estate Ltd', 'Limassol', 'https://www.bazaraki.com/c/mateides/', 14, NULL, 0),
  ('O.R.E CY LTD', 'Nicosia', 'https://www.bazaraki.com/c/cmoreproperties/', 70, NULL, 0),
  ('Ksenia', 'Limassol', 'https://www.bazaraki.com/c/Xenia/', 12, NULL, 0),
  ('Cyprus101', 'Paphos', '', 0, 4.9, 121),
  ('West Coast Properties', 'Paphos', '', 0, 4.6, 88),
  ('G&P Lazarou Estate Agents LTD', 'Nicosia', '', 0, 4.8, 124),
  ('REInvest Real Estate', 'Nicosia', '', 0, 4.8, 23),
  ('REMAX Capital Real Estate Agency Nicosia', 'Nicosia', '', 0, 4.6, 20),
  ('CyprusProperties', 'Larnaca', '', 0, 4.7, 40),
  ('Cyprus Dream Homes', 'Larnaca', '', 0, 4.8, 37),
  ('Trilogy Limassol Seafront', 'Limassol', '', 0, 4.5, 98),
  ('Blue Sky Properties Limassol', 'Limassol', '', 0, 4.7, 26),
  ('KINNIS PROPERTY DEVELOPERS', 'Limassol', '', 0, 4.9, 17),
  ('DevelopersCyprus', 'Limassol', '', 0, 5, 8),
  ('PP Estates', 'Limassol', '', 0, 5, 28),
  ('NCH Real Estate Limassol', 'Limassol', '', 0, 5, 4),
  ('Aristo Developers', 'Paphos', '', 0, 5, 10),
  ('Island blue Property Developer', 'Paphos', '', 0, 4.3, 25),
  ('Property Canvas', 'Paphos', '', 0, 4.8, 17);

-- Remove public insert policy after seeding
-- DROP POLICY "Allow public insert" ON agents;
